site_name: Campylobacter CRISPRscape
site_url: https://localhost:8000/campylobacter-crisprscape
nav:
  - Overview: index.md
  - User manual: manual.md
  - Workflow details:
    - Prepare genomes:
      - Script functions: prepare_genomes.md
      - Metadata: allthebacteria.md
    - CRISPR screening: CRISPR_screening.md
    - CRISPR clustering: clustering_spacers.md
    - SpacePHARER: spacepharer.md
  - Output files: enter_here
  - Development notes: dev_notes.md
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
docs_dir: "doc"
plugins:
  - offline
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: 
      url_download: false
      url_max_size: 33554432
      url_timeout: 10