site_name: Campylobacter CRISPRscape
site_url: https://localhost:8000/campylobacter-crisprscape
nav:
  - CRISPR screening: CRISPR_screening.md
  - Prepare genomes: prepare_genomes.md
  - SpacePHARER: spacepharer.md
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
docs_dir: "doc"
plugins:
  - offline
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: 
      url_download: false
      url_max_size: 33554432
      url_timeout: 10