#!/usr/bin/env python3

# Read the SAM file as generated by KMA to calculate the number
# of mismatches between template (CRISPR spacer) and query (contig).

# In short, it does:
# Read the SAM file, ignoring header lines,
# collect Template ID, query ID and CIGAR string,
# from the CIGAR, extract the number of mismatches 'X',
# insertions 'I' and deletions 'D'.
# Sum these number to calculate the total number of mismatches
# between query and template.
# Return a three-column table:
# Template,Query,Mismatches

from datetime import datetime
import re
import sys  # for writing stdout to log file

from pathlib import Path

samfile = snakemake.input["sam"]
mismatch_table = snakemake.output["table"]

now = re.sub(pattern="\\.[0-9]+", repl="", string=str(datetime.now()))


def read_samfile(inputfile: str, outputfile: str):
    """
    Read a SAM file, skipping header lines and retaining only
    template ID, query ID and CIGAR string.
    """
    with open(outputfile, "w") as outfile:
        # Start by writing a header
        outfile.write("Contig\tSpacer_cluster\tMismatches\n")

        with open(inputfile, "r") as infile:
            print(f"[{now}] Start reading SAM file ({inputfile})...")
            for line in infile:
                if line.startswith("@"):
                    # Is a header!
                    continue
                else:
                    line_elements = line.split("\t")
                    template_id = line_elements[0]
                    query_id = line_elements[2]
                    cigar = line_elements[5]
                    mismatches = process_cigar(cigar=cigar)

                    outfile.write(f"{template_id}\t{query_id}\t{mismatches}\n")

    print(f"[{now}] Done reading! Wrote output to {outputfile}!")

    return 0


def process_cigar(cigar: str):
    """
    Read a CIGAR string to calculate the number of mismatches
    """
    # Match any number followed by X (mismatch) I (insertion) or D (deletion)
    mismatch_pattern = r"[0-9]+[XID]"

    matches = re.findall(pattern=mismatch_pattern, string=cigar)

    mismatches = sum([int(element.rstrip("DIX")) for element in matches])

    return mismatches


def main():
    with open(snakemake.log[0], "w") as sys.stdout:
        # Check if the provided file exists
        assert Path(samfile).is_file(), (
            "%s does not exist! Please provide a valid SAM file." % samfile
        )

        read_samfile(inputfile=samfile, outputfile=mismatch_table)

    return 0


if __name__ == "__main__":
    exit(main())
