jobs: 24
use-conda: true
jobname: Smk-{name}.{jobid}
printshellcmds: true
latency-wait: 60
rerun-incomplete: true
keep-going: true
consider-ancient:
  crisprcastyper: batch
  genomad: fasta
  jaeger: batch
  concatenate_batches: 0
