# Snakemake config file for CRISPR screening workflow

### 1. Input/output parameters ###

input_directory: "data/tmp/ATB/"
output_directory: "data/tmp/"


### 2. Tool-specific parameters ###

cctyper:
  threads: 4