# Snakemake config file for CRISPR screening workflow

mlst:
  threads: 20
  species: "campylobacter jejuni/coli"

cctyper:
  threads: 20

padloc:
  threads: 20

parse_cctyper:
  threads: 20

extract_sequences:
  threads: 20

extract_arrays:
  threads: 10

genomad:
  threads: 20

jaeger:
  threads: 16

crispridentify:
  threads: 20

download_spacepharer_databases:
  threads: 4

spacepharer:
  threads: 20

kma:
  threads: 16