# Snakemake config file for CRISPR screening workflow

### 1. Input/output parameters ###

input_directory: "data/tmp/ATB/"
output_directory: "data/tmp/"

genomad_database: "data/genomad_db/"

### 2. Tool-specific parameters ###

cctyper:
  threads: 20

parse_cctyper:
  threads: 20

extract_arrays:
  threads: 10

extract_sequences:
  threads: 10

genomad:
  threads: 20

jaeger:
  threads: 16

crispridentify:
  threads: 20
