# Snakemake config file for CRISPR screening workflow

### 1. Input/output parameters ###

input_directory: "data/tmp/ATB/"
output_directory: "data/tmp/"

genomad_database: "data/genomad_db/"
spacepharer_phage_database: "data/raw/phagescope/"
spacepharer_plasmid_database: "data/raw/PLSDB/"
### 2. Tool-specific parameters ###

mlst:
  threads: 20
  species: "campylobacter jejuni/coli"

cctyper:
  threads: 20

padloc:
  threads: 20

parse_cctyper:
  threads: 20

extract_sequences:
  threads: 20

extract_arrays:
  threads: 10

genomad:
  threads: 20

jaeger:
  threads: 16

crispridentify:
  threads: 20
